//USE [master]
//GO
///****** Object:  Database [Cities]    Script Date: 5/1/2021 4:03:54 PM ******/
//CREATE DATABASE [Cities]
// CONTAINMENT = NONE
// ON  PRIMARY 
//( NAME = N'Cities', FILENAME = N'C:\Program Files\Microsoft SQL Server\.\MSSQL\DATA\Cities.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
// LOG ON 
//( NAME = N'Cities_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\.\MSSQL\DATA\Cities_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
//GO
//ALTER DATABASE [Cities] SET COMPATIBILITY_LEVEL = 140
//GO
//IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
//begin
//EXEC [Cities].[dbo].[sp_fulltext_database] @action = 'enable'
//end
//GO
//ALTER DATABASE [Cities] SET ANSI_NULL_DEFAULT OFF 
//GO
//ALTER DATABASE [Cities] SET ANSI_NULLS OFF 
//GO
//ALTER DATABASE [Cities] SET ANSI_PADDING OFF 
//GO
//ALTER DATABASE [Cities] SET ANSI_WARNINGS OFF 
//GO
//ALTER DATABASE [Cities] SET ARITHABORT OFF 
//GO
//ALTER DATABASE [Cities] SET AUTO_CLOSE OFF 
//GO
//ALTER DATABASE [Cities] SET AUTO_SHRINK OFF 
//GO
//ALTER DATABASE [Cities] SET AUTO_UPDATE_STATISTICS ON 
//GO
//ALTER DATABASE [Cities] SET CURSOR_CLOSE_ON_COMMIT OFF 
//GO
//ALTER DATABASE [Cities] SET CURSOR_DEFAULT  GLOBAL 
//GO
//ALTER DATABASE [Cities] SET CONCAT_NULL_YIELDS_NULL OFF 
//GO
//ALTER DATABASE [Cities] SET NUMERIC_ROUNDABORT OFF 
//GO
//ALTER DATABASE [Cities] SET QUOTED_IDENTIFIER OFF 
//GO
//ALTER DATABASE [Cities] SET RECURSIVE_TRIGGERS OFF 
//GO
//ALTER DATABASE [Cities] SET  DISABLE_BROKER 
//GO
//ALTER DATABASE [Cities] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
//GO
//ALTER DATABASE [Cities] SET DATE_CORRELATION_OPTIMIZATION OFF 
//GO
//ALTER DATABASE [Cities] SET TRUSTWORTHY OFF 
//GO
//ALTER DATABASE [Cities] SET ALLOW_SNAPSHOT_ISOLATION OFF 
//GO
//ALTER DATABASE [Cities] SET PARAMETERIZATION SIMPLE 
//GO
//ALTER DATABASE [Cities] SET READ_COMMITTED_SNAPSHOT OFF 
//GO
//ALTER DATABASE [Cities] SET HONOR_BROKER_PRIORITY OFF 
//GO
//ALTER DATABASE [Cities] SET RECOVERY SIMPLE 
//GO
//ALTER DATABASE [Cities] SET  MULTI_USER 
//GO
//ALTER DATABASE [Cities] SET PAGE_VERIFY CHECKSUM  
//GO
//ALTER DATABASE [Cities] SET DB_CHAINING OFF 
//GO
//ALTER DATABASE [Cities] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
//GO
//ALTER DATABASE [Cities] SET TARGET_RECOVERY_TIME = 60 SECONDS 
//GO
//ALTER DATABASE [Cities] SET DELAYED_DURABILITY = DISABLED 
//GO
//ALTER DATABASE [Cities] SET QUERY_STORE = OFF
//GO
//USE [Cities]
//GO
///****** Object:  Table [dbo].[cities]    Script Date: 5/1/2021 4:03:55 PM ******/
//SET ANSI_NULLS ON
//GO
//SET QUOTED_IDENTIFIER ON
//GO
//CREATE TABLE [dbo].[cities](
//	[city_id] [int] NOT NULL,
//	[city_name] [varchar](50) NOT NULL
//) ON [PRIMARY]
//GO
//USE [master]
//GO
//ALTER DATABASE [Cities] SET  READ_WRITE 
//GO